#!name=Emby
#!desc=Emby解锁会员
#!homepage=https://www.greenfishpowered.cn
#!author=GreenFishStudio
#!icon=https://cdn.jsdelivr.net/gh/GreenFishStudio/GreenFish-Blog@main/Logo/logor.png
[Script]
EmbyPremiere = type=http-response,script-path=https://fastly.jsdelivr.net/gh/rartv/SurgeScript@main/EmbyPremiere/EmbyPremiere.js,pattern=^https?:\/\/mb3admin.com\/admin\/service\/registration\/validateDevice,max-size=131072,requires-body=true,timeout=10,enable=true

[MITM]
hostname = mb3admin.com
